{% set version = "0.9-7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-glmmadaptive
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GLMMadaptive_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GLMMadaptive/GLMMadaptive_{{ version }}.tar.gz
  sha256: 3f1cc2e49099d1110ada120ec1da806546e00aa142a70a762af3921794f6e13c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-matrixstats
    - r-nlme
  run:
    - r-base
    - r-mass
    - r-matrixstats
    - r-nlme

test:
  commands:
    - $R -e "library('GLMMadaptive')"           # [not win]
    - "\"%R%\" -e \"library('GLMMadaptive')\""  # [win]

about:
  home: https://drizopoulos.github.io/GLMMadaptive/
  dev_url: https://github.com/drizopoulos/GLMMadaptive
  license: GPL-3.0-or-later
  summary: Fits generalized linear mixed models for a single grouping factor under maximum likelihood approximating the integrals over the random effects with an adaptive Gaussian quadrature rule; Jose C. Pinheiro and Douglas M. Bates (1995) <doi:10.1080/10618600.1995.10474663>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach
