{% set version = '0.9-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-glmmadaptive
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GLMMadaptive_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GLMMadaptive/GLMMadaptive_{{ version }}.tar.gz
  sha256: 233b0c557eb6bfde9a8a6ef8ba4917a21f1a27cf29c3a2d3c5bb140cec275043

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-matrixstats
    - r-nlme
  run:
    - r-base
    - r-mass
    - r-matrixstats
    - r-nlme

test:
  commands:
    - $R -e "library('GLMMadaptive')"           # [not win]
    - "\"%R%\" -e \"library('GLMMadaptive')\""  # [win]

about:
  home: https://drizopoulos.github.io/GLMMadaptive/, https://github.com/drizopoulos/GLMMadaptive
  license: GPL-3.0-or-later
  summary: Fits generalized linear mixed models for a single grouping factor under maximum likelihood
    approximating the integrals over the random effects with an adaptive Gaussian quadrature
    rule; Jose C. Pinheiro and Douglas M. Bates (1995) <doi:10.1080/10618600.1995.10474663>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: GLMMadaptive
# Title: Generalized Linear Mixed Models using Adaptive Gaussian Quadrature
# Version: 0.9-0
# Authors@R: person("Dimitris", "Rizopoulos", email = "d.rizopoulos@erasmusmc.nl", role = c("aut", "cre"), comment = c(ORCID = '0000-0001-9397-0900'))
# Date: 2023-06-22
# Maintainer: Dimitris Rizopoulos <d.rizopoulos@erasmusmc.nl>
# BugReports: https://github.com/drizopoulos/GLMMadaptive/issues
# Description: Fits generalized linear mixed models for a single grouping factor under maximum likelihood approximating the integrals over the random effects with an adaptive Gaussian quadrature rule; Jose C. Pinheiro and Douglas M. Bates (1995) <doi:10.1080/10618600.1995.10474663>.
# Imports: MASS, nlme, parallel, matrixStats
# Suggests: lattice, knitr, rmarkdown, pkgdown, multcomp, emmeans, estimability, effects, DHARMa, optimParallel
# Encoding: UTF-8
# LazyLoad: yes
# License: GPL (>= 3)
# URL: https://drizopoulos.github.io/GLMMadaptive/, https://github.com/drizopoulos/GLMMadaptive
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2023-06-22 07:06:23 UTC; drizo
# Author: Dimitris Rizopoulos [aut, cre] (<https://orcid.org/0000-0001-9397-0900>)
# Repository: CRAN
# Date/Publication: 2023-06-22 07:40:08 UTC
